apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-flask-servicemonitor
  namespace: devops
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: devops-flask
  namespaceSelector:
    matchNames:
      - devops
  endpoints:
    - port: 5000
      path: /metrics
      interval: 15s
