apiVersion: v1
kind: Service
metadata:
  name: devops-flask
  namespace: devops
  labels:
    app: devops-flask
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: devops-flask
